spring:
    main:
        allow-circular-references: true
    data:
      mongodb:
          uri: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.1.9
          database: local

endpoint:
    redskyUrl: https://redsky-uat.perf.target.com/redsky_aggregations/v1/redsky/case_study_v1